check-private-items = true
max-fn-params-bools = 1
single-char-binding-names-threshold = 0

disallowed-types = [
  # { path = "…", reason = "…" }
]

standard-macro-braces = [
  { name = "join", brace = "[" },
  { name = "tokio::join", brace = "[" },
  { name = "try_join", brace = "[" },
  { name = "tokio::try_join", brace = "[" },
  { name = "query", brace = "(" },
  { name = "sqlx::query", brace = "(" },
  { name = "query_as", brace = "(" },
  { name = "sqlx::query_as", brace = "(" },
  { name = "query_scalar", brace = "(" },
  { name = "sqlx::query_scalar", brace = "(" },
]
