# https://rust-lang.github.io/rustfmt?version=v1.7.0

edition = "2021"
version = "Two"
unstable_features = true

hard_tabs = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_modules = false

format_macro_matchers = true
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
