# https://rust-lang.github.io/rustfmt?version=v1.7.0

edition = "2021"
version = "Two"
unstable_features = true

hard_tabs = true

max_width = 100
fn_call_width = 69
single_line_let_else_max_width = 0
struct_lit_width = 69
attr_fn_like_width = 90

group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_modules = false

format_macro_matchers = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
