# https://rust-lang.github.io/rustfmt/?version=master

edition = "2021"
style_edition = "2024"
unstable_features = true

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
skip_macro_invocations = ["assert", "assert_eq", "assert_ne"]
format_strings = true
hard_tabs = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
single_line_let_else_max_width = 0
wrap_comments = true
