[workspace]
resolver = "2"
members = ["cs2kz", "cs2kz-api", "cs2kz-api-spec-generator"]

[workspace.dependencies.color-eyre]
version = "0.6"

[workspace.dependencies.thiserror]
version = "1"

[workspace.dependencies.tracing]
version = "0.1"

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[workspace.dependencies.dotenvy]
version = "0.15"

[workspace.dependencies.clap]
version = "4"
features = ["derive"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1"

[workspace.dependencies.rand]
version = "0.8"

[workspace.dependencies.chrono]
version = "0.4"
default-features = false
features = ["std", "serde"]

[workspace.dependencies.tokio]
version = "1"
default-features = false
features = ["rt-multi-thread", "sync", "tracing", "macros"]

[workspace.dependencies.sqlx]
version = "0.7"
default-features = false
features = ["macros", "rust_decimal", "chrono", "runtime-tokio", "tls-rustls", "mysql"]

[workspace.dependencies.utoipa]
version = "4"
features = ["chrono", "axum_extras"]
