[package]
name = "cs2kz-api"
version = "0.0.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
description = "The backend API for CS2KZ"
readme = "./README.md"
homepage = "https://cs2.kz"
repository = "https://github.com/KZGlobalTeam/cs2kz-api.git"
license-file = "./LICENSE"
publish = false

[profile.release]
debug = true

[features]
console = ["dep:console-subscriber", "tokio/tracing"]
production = []

[dependencies.cs2kz]
path = "./crates/cs2kz"
features = ["serde", "utoipa", "sqlx"]

[dependencies.cs2kz-api-macros]
path = "./crates/cs2kz-api-macros"

[dependencies.dotenvy]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.console-subscriber]
version = "0.2.0"
optional = true

[dependencies.axum]
version = "0.7.4"
default-features = false
features = [
  "http1",
  "tracing",
  "tokio",
  "json",
  "query",
  "macros",
]

[dependencies.axum-extra]
version = "0.9.1"
features = ["cookie", "typed-header", "query"]

[dependencies.tower-http]
version = "0.5.1"
features = ["cors", "trace"]

[dependencies.crossbeam]
version = "0.8.4"

[dependencies.sqlx]
version = "0.7.3"
default-features = false
features = [
  "runtime-tokio-rustls",
  "mysql",
  "macros",
  "chrono",
  "time",
]

[dependencies.url]
workspace = true

[dependencies.semver]
version = "1.0.21"
features = ["serde"]

[dependencies.reqwest]
version = "0.11.24"
default-features = false
features = ["rustls-tls", "json"]

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.serde_urlencoded]
version = "0.7.1"

[dependencies.jsonwebtoken]
version = "9.2.0"

[dependencies.utoipa]
version = "4.2.0"
features = [
  "url",
  "axum_extras",
  "chrono",
  "non_strict_integers",
  "preserve_order",
  "preserve_path_order",
  "debug",
]

[dependencies.axum-swagger-ui]
version = "0.3.0"

[dependencies.itertools]
workspace = true

[dependencies.crc32fast]
version = "1.3.2"

[dependencies.smart-debug]
version = "0.0.3"

[dependencies.time]
version = "0.3.31"
features = ["macros"]

[dependencies.chrono]
version = "0.4.31"
default-features = false
features = ["std", "clock", "serde"]

[dependencies.rand]
version = "0.8.5"

[dev-dependencies]
color-eyre = "0.6.2"
ctor = "0.2.6"

[workspace]
resolver = "2"
members = [
  "crates/cs2kz",
  "crates/cs2kz-api-macros",
  "crates/spec-generator",
]

[workspace.dependencies.dotenvy]
version = "0.15.7"

[workspace.dependencies.thiserror]
version = "1.0.56"

[workspace.dependencies.tokio]
version = "1.36.0"
features = ["rt-multi-thread", "net", "process", "macros"]

[workspace.dependencies.tracing]
version = "0.1.40"

[workspace.dependencies.tracing-subscriber]
version = "0.3.18"
default-features = false
features = [
  "std",
  "fmt",
  "ansi",
  "env-filter",
  "time",
  "json",
]

[workspace.dependencies.url]
version = "2.5.0"
features = ["serde"]

[workspace.dependencies.serde]
version = "1.0.196"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.113"

[workspace.dependencies.itertools]
version = "0.12.0"
