[package]
name = "cs2kz-api"
version = "0.0.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
readme = "./README.md"
homepage = "https://cs2kz.org"
repository = "https://github.com/KZGlobalTeam/cs2kz-api"
license-file = "./LICENSE"
publish = false

[lints.rust]
elided_lifetimes_in_paths = "deny"
macro_use_extern_crate = "deny"
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"
missing_docs = "deny"
non_ascii_idents = "deny"
single_use_lifetimes = "warn"

[lints.rustdoc]
broken_intra_doc_links = "deny"

[lints.clippy]
absolute_paths = "warn"
as_underscore = "warn"
bool_comparison = "deny"
bool_to_int_with_if = "deny"
cast_possible_truncation = "deny"
clone_on_ref_ptr = "deny"
cognitive_complexity = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
future_not_send = "warn"
ignored_unit_patterns = "deny"
missing_docs_in_private_items = "deny"
new_without_default = "allow"
redundant_closure = "allow"
todo = "warn"
unimplemented = "deny"

[workspace]
resolver = "2"
members = ["crates/spec-generator", "crates/macros"]

[features]
production = []
console = ["dep:console-subscriber", "tokio/tracing"]

[workspace.dependencies.eyre]
version = "0.6"

[dependencies.cs2kz]
path = "./crates/cs2kz"
features = ["serde", "sqlx", "utoipa"]

[dependencies.thiserror]
version = "1.0"

[dependencies.eyre]
workspace = true

[dependencies.tokio]
version = "1.36"
features = ["rt-multi-thread", "net", "process", "signal", "macros"]

[dependencies.futures]
version = "0.3"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["rustls-tls", "json"]

[dependencies.axum]
version = "0.7"
default-features = false
features = ["http1", "http2", "tokio", "query", "json", "macros"]

[dependencies.axum-extra]
version = "0.9"
features = ["typed-header", "cookie", "query"]

[dependencies.tower-http]
version = "0.5"
features = ["trace", "cors"]

[dependencies.sqlx]
version = "0.7"
default-features = false
features = [
  "runtime-tokio-rustls",
  "mysql",
  "chrono",
  "time",
  "json",
  "uuid",
  "macros",
  "migrate",
]

[dependencies.utoipa]
version = "4.2"
features = [
  "debug",
  "preserve_order",
  "preserve_path_order",
  "non_strict_integers",
  "url",
  "chrono",
  "uuid",
  "axum_extras",
]

[dependencies.utoipa-swagger-ui]
version = "6.0"
features = ["axum"]

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["std", "fmt", "ansi", "json", "env-filter"]

[dependencies.tracing-appender]
version = "0.2"

[dependencies.console-subscriber]
version = "0.2"
optional = true

[dependencies.dotenvy]
version = "0.15"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.serde_urlencoded]
version = "0.7"

[dependencies.envy]
version = "0.4"

[dependencies.url]
version = "2.5"
features = ["serde"]

[dependencies.rand]
version = "0.8"

[dependencies.uuid]
version = "1.7"
features = ["v4", "fast-rng", "serde"]

[dependencies.jsonwebtoken]
version = "9.2"

[dependencies.semver]
version = "1.0"
features = ["serde"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["std", "serde"]

[dependencies.time]
version = "0.3"

[dependencies.itertools]
version = "0.12"

[dependencies.derive_more]
version = "1.0.0-beta.6"
default-features = false
features = ["display", "debug", "deref", "deref_mut", "from", "into"]

[dependencies.crc32fast]
version = "1.4"

[dev-dependencies.ctor]
version = "0.2"

[dev-dependencies.cs2kz-api-macros]
path = "./crates/macros"
