[workspace]
resolver = "2"
members = ["cs2kz", "cs2kz-api"]

[workspace.dependencies.color-eyre]
version = "0.6.2"

[workspace.dependencies.thiserror]
version = "1.0.48"

[workspace.dependencies.tracing]
version = "0.1.37"

[workspace.dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter"]

[workspace.dependencies.dotenvy]
version = "0.15.7"

[workspace.dependencies.clap]
version = "4.4.4"
features = ["derive"]

[workspace.dependencies.serde]
version = "1.0.188"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.107"

[workspace.dependencies.rand]
version = "0.8.5"

[workspace.dependencies.tokio]
version = "1.32.0"
default-features = false
features = ["rt-multi-thread", "sync", "tracing", "macros"]

[workspace.dependencies.sqlx]
version = "0.7.2"
default-features = false
features = ["macros", "rust_decimal", "chrono", "runtime-tokio", "tls-rustls", "mysql"]

[workspace.dependencies.utoipa]
version = "3.5.0"
features = ["chrono", "axum_extras"]
