services:
  database:
    image: mariadb:11.0
    environment:
      MARIADB_USER: schnose
      MARIADB_PASSWORD: very-secure-password
      MARIADB_DATABASE: kz
      MARIADB_ROOT_PASSWORD: very-secure-password
    ports:
      - ${CS2KZ_API_DATABASE_PORT-3306}:3306
    volumes:
      - cs2kz-database:/var/lib/mysql

volumes:
  cs2kz-database:
