services:
  database:
    image: mariadb:11.0
    environment:
      MARIADB_USER: schnose
      MARIADB_PASSWORD: csgo-kz-is-dead-boys
      MARIADB_DATABASE: cs2kz
      MARIADB_ROOT_PASSWORD: csgo-kz-is-dead-boys
    ports:
      - ${DATABASE_PORT-3306}:3306
    volumes:
      - cs2kz-database:/var/lib/mysql

volumes:
  cs2kz-database:
