unstable_features = true

edition = "2024"
style_edition = "2024"

newline_style = "Unix"

skip_macro_invocations = [
  "assert",
  "debug_assert",
  "assert_eq",
  "debug_assert_eq",
  "assert_ne",
  "debug_assert_ne",
  "assert_matches",
  "debug_assert_matches",
]


## indentation and line width

hard_tabs = true
use_small_heuristics = "Max"

chain_width = 75
single_line_let_else_max_width = 0

condense_wildcard_suffixes = true
overflow_delimited_expr = true
format_strings = true

## comments

normalize_comments = true
normalize_doc_attributes = true

## trailing commas

match_block_trailing_comma = true

## items

brace_style = "AlwaysNextLine"
empty_item_single_line = false
group_imports = "One"
imports_granularity = "One"
imports_layout = "HorizontalVertical"
