[toolchain]
channel = "nightly-2025-04-17"
profile = "minimal"
components = [
  "rustc",
  "rust-std",
  "rust-src",
  "rust-docs",
  "cargo",
  "clippy",
  "rustfmt",
  "rust-analyzer",
]
targets = ["aarch64-unknown-linux-gnu"]
