[package]
name = "spec-generator"
version = "0.0.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
description = "CLI tool for generating a JSON representation of the API's OpenAPI specification"
readme = "../../README.md"
homepage = "https://cs2.kz"
repository = "https://github.com/KZGlobalTeam/cs2kz-api.git"
license-file = "../../LICENSE"

[dependencies.color-eyre]
version = "0.6.2"

[dependencies.cs2kz-api]
path = "../../"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.similar]
version = "2"
