[package]
name = "cs2kz-api"
version = "0.0.0"
readme = "../README.md"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dev-dependencies.ctor]
version = "0.2"

[dev-dependencies.anyhow]
version = "1.0"
