[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.'cfg(all(target_os = "linux", any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64")))']
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]
