# Example of the API's configuration file.
#
# The actual file is called `api.toml` and is gitignored by default.
# All of the values in here have default values. See the `Config` struct in the `cs2kz-api` crate.

address = "0.0.0.0"
port = 42069
enable_logging = true
database_url = "mysql://kz:csgo-kz-is-dead-boys@127.0.0.1:8070/cs2kz-api"
