[package]
name = "cs2kz-api"
version = "0.0.0"
edition = "2021"

[dependencies]
color-eyre = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }

[dependencies.cs2kz]
path = "../cs2kz/"
features = ["serde", "utoipa"]

[dependencies.axum]
version = "0.6.20"
default-features = false
features = ["http1", "query", "tokio", "tracing", "macros"]

[dependencies.hyper]
version = "0.14.27"

[dependencies.tower-http]
version = "0.4.4"
features = ["cors"]

[dependencies.utoipa-swagger-ui]
version = "3.1.5"
features = ["axum"]
