name: Checks

permissions:
  contents: read

on:
  push:
    branches: ['master', 'bingus'] # FIXME
  pull_request:

# If new code is pushed to a PR branch, cancel in progress workflows for that
# PR. This Ensures that we don't waste CI time, and returns results quicker.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: cachix/cachix-action@v14
      with:
        name: cs2kz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: run checks
      run: nix flake check .#
    - uses: DeterminateSystems/flake-checker-action@main
