name: CS2KZ API

on:
  push:
    branches: ['master']
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compilation and Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy
      - run: cargo clippy --all-features --workspace -- -D warnings

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: rustfmt
      - run: cargo +nightly fmt --all

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
      - run: cargo doc --all-features --workspace --document-private-items --no-deps
      - run: cargo run --package spec-generator -- --check api-spec.json
