name: Nix

permissions:
  contents: read

on:
  push:
    branches: ['master', 'take1337']
  pull_request:

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix flake check
