name: OpenAPI Schema

permissions:
  contents: read

on:
  push:
    branches: ['master']

jobs:
  openapi:
    name: OpenAPI Schema
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: generate schema
      run: nix run .#openapi-schema > openapi.json
    - uses: actions/upload-artifact@v4
      with:
        name: openapi.json
        path: openapi.json
