# This is the main CI workflow that runs the test suite on all pushes to main and all pull requests.
#
# See static-analysis.yml for information about how the concurrency cancellation works.

name: test suite

permissions:
  contents: read

on:
  push:
    branches: ['master']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        run: cargo generate-lockfile
      - name: cargo test --locked
        env:
          STEAM_WEB_API_KEY: ${{ secrets.STEAM_WEB_API_KEY }}
        run: cargo test --workspace --locked --all-features --all-targets -- --nocapture
